In [17]:
import numpy
from helper import laplace_solution, l2_norm, plot_3d

ModuleNotFoundError: No module named 'helper'

In [13]:
def jacobi(u, b, iters):
    ny, nx = u.shape
    
    for it in range(iters):
    
        uk = u.copy()
        for j in range (1, ny-1):
            for i in range(1, nx-1):
                u[j,i] = 0.25 * (uk[j-1,i] + uk[j, i-1] - 4 * uk[j,i] + uk[j, i+1] + u[j+1,i] - b[j,i])
        
        
        #rdiff = check_convergence(p, pn)
        return u

In [14]:
nx = ny = 5
dx = 0.25
u = numpy.zeros((ny,nx))
b = numpy.ones((ny,nx)) * 0.5* .25 * .25

u[:,0] =1
u[0,:] = 1
u[-1::] = 1


u = jacobi(u, b ,1)
print(u[1:-1, 1:-1])



[[ 0.4921875  0.2421875  0.2421875]
 [ 0.2421875 -0.0078125 -0.0078125]
 [ 0.4921875  0.2421875  0.2421875]]


In [18]:
def laplace_2d_gaus_sedel(p0, b, iters):
    p = p0.copy()
    ny, nx = p0.shape
    
    for i in range(iters):
        pn = p.copy()
        
        for j in range(1, ny -1):
            for i in range(1, nx- 1):
                p[j, i] = 0.25 * (p[j-1, i] + p[j, i-1] + pn[j, i+1]
                                 + pn[j+1, i] - b[j,i])
    return p

In [19]:
u = laplace_2d_gaus_sedel(u, b ,1)
print(u[1:-1, 1:-1])

[[0.61328125 0.45410156 0.35375977]
 [0.51660156 0.29345703 0.21453857]
 [0.68188477 0.54656982 0.4324646 ]]


In [27]:
def poisson2d_sor(p0, b, iters, w=0.2):
    p = p0.copy()
    ny, nx = p0.shape
    
    for i in range(iters):
        pn = p.copy()
        for j in range(1, ny-1):
            for i in range(1, nx -1):
                p[j,i] = ((1- w)* pn[j,i] + 
                         0.25 * w * (p[j-1, i]
                                    + p[j, i-1] + pn[j, i+1] + pn[j+1, i]
                                    - b[j,i]))
    return p
        
    

In [28]:
u = poisson2d_sor(u, b, 1, w=0.2)
print(u[1:-1, 1:-1])

[[0.63759766 0.47595947 0.36597021]
 [0.54236572 0.3221748  0.22609884]
 [0.69839209 0.55834493 0.43363137]]
